### ISSUE TITLE
C++ Exceptions

### ISSUE THREAD

**Issue by CEXT-Dan** [CEXT-Dan/PyRx#110]
### Discussed in https://github.com/CEXT-Dan/PyRx/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **gswifort** September  5, 2024</sup>
To make working with C++ exceptions easier I added tools to translate general C++ exceptions (`RuntimeError`) to specific types. You can see the implementation [here](https://github.com/gswifort/PyRx/blob/50eeafd5f2bf89deaacabe86546358abd73339aa/pyrx/exceptions.py).
Usage looks like this:

```py
text = Db.Text()
text_id = db.addToModelspace(text)
with cast_to_arx_exception:
    Db.Text(text_id, Db.OpenMode.kForRead)  # raises pyrx.exceptions.eWasOpenForWrite
```
I wonder if I should stick to this path or if you have a better idea..? Maybe you want to implement something similar in C++?</div>

**Comment by CEXT-Dan** [comment]
bump

**Comment by CEXT-Dan** [comment]
Thinking about this a bit more.
AutoCAD ARX does not throw exceptions, but returns and error code, there’s many hundreds of codes. 
Originally, I did the same with the wrappers, I actually prefer the error code handling in C++. But I did not like it with python

1, Correct me if I’m wrong, but the error code model does really fit in a scripting language, you would have to check ‘every’ function.
2, Python does not support out parameters well, since some objects are immutable, so every function would have to return a tuple (Acad::ErrorStatus, Value)

To me it made sense to throw exceptions with the error code as a string

Digging in to this a bit deeper, using your example “pyrx.exceptions.eWasOpenForWrite”, but there’s also the possibility of eWasErased, eWasOpenForUndo, eWasNotifying, eOnLockedLayer, eAtMaxReaders, eIsWriteProtected, and more.

Now won’t you be back to using exceptions as error codes if you need to handle these possibilities?

**Comment by CEXT-Dan** [comment]
Thinking about alternatives as it seems excessive to wrap all ~400 error codes in their own classes 
what about something like 

```Python

from pyrx_imp import Ap, Db, Ed, Ge, Gi, Gs, Rx

def PyRxCmd_doit():
    try:
        # do something bad
    except Ap.ErrorStatus as err:
        match err.code:
            case eWasOpenForWrite:
                pass
            case eOnLockedLayer:
                pass
            case _:
                raise # rethrow
```

**Comment by gswifort** [comment]
It seems ok. It is important that all codes are in e.g. some enum or in the Ap module namespace.
