### ISSUE TITLE
ZWCAD crashes during ``getBlockName()`` on empty block reference name

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#112]
The attached dwg file contains one block reference which has an empty name. When calling `Db.BlockReference.getBlockName()` ZWCAD crashes.

![image](https://github.com/user-attachments/assets/eed3400c-39da-4dbb-b5cd-405a064fe34b)

```py
import traceback
from pyrx_imp import Db

def PyRxCmd_doit():
    try:
        db=Db.curDb()
        msp=Db.BlockTableRecord(db.modelSpaceId())
        bref = Db.BlockReference(msp.objectIds()[0])
        bref.getBlockName()  # crashes
    except Exception:
        traceback.print_exc()
```

[INSERT_BUG_getBlockName.zip](https://github.com/user-attachments/files/16926754/INSERT_BUG_getBlockName.zip)

**Comment by CEXT-Dan** [comment]
Hi, 
drawing is corrupt 

Command: AUDIT
Fix the errors detected? [Yes/No] <No>: y
AcDbBlockReference BlockTableRecord (0) Invalid Created
162 objects audited
E:\INSERT_BUG_getBlockName.dwg
Total errors found during audit 1, fixed 1 


Also how do you know msp.objectIds()[0] is a block? It could be a line

**Comment by gswifort** [comment]
> Also how do you know msp.objectIds()[0] is a block? It could be a line

![image](https://github.com/user-attachments/assets/9cce2482-f632-43af-a7b6-c95cb8b5e15a)

It's true, the drawing is damaged, the question is whether zwcad should crash in such a situation..?

**Comment by CEXT-Dan** [comment]
it works for me, if the first ID in model space is a reference
if its a line, I get invalid type exception
on a new drawing, I get and index out of range

**Comment by CEXT-Dan** [comment]
use the filter argument

```Python
def PyRxCmd_doit():
    try:
        db = Db.curDb()
        msp = Db.BlockTableRecord(db.modelSpaceId())
        refs = [Db.BlockReference(id) for id in msp.objectIds(Db.BlockReference.desc())]
        names = [ref.getBlockName() for ref in refs]
        print(names)
    except Exception:
        traceback.print_exc()
```

**Comment by gswifort** [comment]
Your code, on the file I sent, ends before the `print` instruction and blocks the database, I can't add anything to msp later. The code below should print `names=[<...>]`, it doesn't print anything for me.

```py
import traceback

from pyrx_imp import Db


def PyRxCmd_doit3():
    try:
        db = Db.curDb()
        msp = Db.BlockTableRecord(db.modelSpaceId())
        refs = [Db.BlockReference(id) for id in msp.objectIds(Db.BlockReference.desc())]
        names = [ref.getBlockName() for ref in refs]
        print(f"{names=}")
    except Exception:
        traceback.print_exc()
```

**Comment by CEXT-Dan** [comment]
I added an exception for this case

```
Command: DOIT3
Traceback (most recent call last):
  File "M:\Dev\Projects\PyRxGit\PySamples\_doit.py", line 9, in PyRxCmd_doit3
    names = [ref.getBlockName() for ref in refs]
             ^^^^^^^^^^^^^^^^^^
RuntimeError: 
Exception!(eNullObjectId), function getBlockName, Line 212, File PyDbEnts.cpp: 
```
