### ISSUE TITLE
Adding an object to the database breaks the command

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#113]
After adding the object to the side database, the function executes completely but does not return a result and ends the command invocation (without throwing any error). In the following example, "Before task" will be printed, the `task()` function executes completely but does not return a result and "After task" will not be printed.
The behavior is the same for any function that adds something to the database:
- `db.addToModelspace`
- `db.addToCurrentspace`
- `db.addObject`
- `btr.appendAcDbEntities`
- `btr.appendAcDbEntity`

```py
import traceback

from pyrx_imp import Db, Ge


def task():
    db = Db.Database()
    line = Db.Line(Ge.Point3d(0.0, 0.0, 0.0), Ge.Point3d(100.0, 100.0, 0.0))
    id = db.addToModelspace(line)
    print(id)


def task_wrapper():
    print("Before task")
    task()
    print("After task")


def PyRxCmd_doit():
    try:
        task_wrapper()
    except Exception:
        traceback.print_exc()
```

*ZWCAD 25.00_2024.05.09(#11749-508f7afbe61)_x64*
*PyRx version <1.3.033.20240829>* (also *1.3.034*)

**Comment by CEXT-Dan** [comment]
yep, it's a known issue,  the problem is that python's garbage collector deletes objects in order of their creation. So, in function task, db is deleted before the line, but the line is still opened for write, with an invalid pointer because db is null.

Line must garbage collected before db, see testSideDatabase.py where I explore different methods to handle this.

**Comment by gswifort** [comment]
I guess I'm not coping with this again..
What is wrong with this sample?

```py
from pyrx import Db, Ge


def add_attr(db: Db.Database):
    mtext = Db.MText()
    mtext.setContents("TEST")
    # db.addObject(mtext)

    attr = Db.AttributeDefinition()
    attr.setTag("TEST")
    attr.setPosition(Ge.Point3d(0.0, 0.0, 0.0))
    attr.setPrompt("TEST")
    attr.setMTextAttributeDefinition(mtext)

    db.addToModelspace(attr)


def PyRxCmd_doit():
    try:
        db = Db.curDb()
        add_attr(db)
    except Exception:
        import traceback

        traceback.print_exc()

```

**Comment by CEXT-Dan** [comment]
Thanks for the report, I’ll fix it

**Comment by CEXT-Dan** [comment]
This one was weird 
 
AcDbAttributeDefinition::setMTextAttributeDefinition takes ownership 
AcDbAttributeDefinition::getMTextAttributeDefinition returns a clone 
//
AcDbAttributeDefinition::setMTextAttributeDefinitionConst makes a clone
AcDbAttributeDefinition::getMTextAttributeDefinitionConst returns actual pointer

The BRX, ZRX, GRX are missing the const version 
The behavior in PyRx is that , or should be, always use clones. So if you wen to change the value, you must call set again 

```Python
import traceback
from pyrx import Rx, Ge, Gi, Db, Ap, Ed, Ax

def add_attr(db : Db.Database):

    mtext1 = Db.MText()
    mtext1.setDatabaseDefaults(db)
    mtext1.setContents("ATT") 
    
    attr = Db.AttributeDefinition()
    attr.setDatabaseDefaults(db)
    attr.setTag("TEST")
    attr.setPosition(Ge.Point3d(0.0, 0.0, 0.0))
    attr.setPrompt("TEST")
    
    #this is required in AutoCAD
    attr.convertIntoMTextAttributeDefinition(True)
    attr.setMTextAttributeDefinition(mtext1)
    
    mtext2 = attr.getMTextAttributeDefinition()
    mtext2.setContents("NEWATT") 
    attr.setMTextAttributeDefinition(mtext2)
    
    db.addToModelspace(attr)
    
    mtext3 = attr.getMTextAttributeDefinition()
    
    print(mtext3.contents(), attr.textString())
    
    #different pointers
    print(mtext1.intPtr(), mtext2.intPtr())
    
@Ap.Command()
def doit():
    try:
        db = Db.curDb()
        add_attr(db)
    except Exception as err:
        traceback.print_exception(err)

```
