### ISSUE TITLE
``Ax.getApp()`` returns a "random" application

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#116]
1. open a new instance of ZWCAD and save the file, e.g. "1.dwg"
2. open a second instance of ZWCAD and save the file, e.g. "2.dwg"
3. in instance "2" run the code below

```py
from pyrx_impx import Ax, Db

def PyRxCmd_doit():
    try:
        arx_doc_name = Db.curDb().getFilename()
        ax_app = Ax.getApp()
        ax_doc_name = ax_app.ActiveDocument.Name
        print(f"{arx_doc_name=}")
        print(f"{ax_doc_name=}")
    except Exception as e:
        print(e)
```

Result:

```raw
arx_doc_name='D:\\Users\\GSWI\\Download\\2.dwg'
ax_doc_name='1.dwg'
```

In my case ``Ax.getApp()`` returns instance "1", I would expect the instance from which the code is called.

**Comment by CEXT-Dan** [comment]
The call is win32com.client.GetActiveObject, I know this is always an issue with multiple instances with COM, even with VBA and .NET
Did you happen to activate the other instance in-between commands?

Maybe move ax_app = Ax.getApp() to the global space so It’s evaluated on load

Side note, there’s a function Ap.Application.acadGetIDispatch(), but I don’t know how to plug it into win32com yet

**Comment by CEXT-Dan** [comment]
another option might be to cache the instance of the app in  Ax.getApp()
if not none, get the app, else return the instance

**Comment by gswifort** [comment]
Moving ``ax_app = Ax.getApp() `` to the global namespace does nothing. 

I've already tried ``acadGetIDispatch``, it returns the same in both instances.

**Comment by CEXT-Dan** [comment]
Yeah, for me I always get the first app that was launched, seems like a flaw in win32com. not sure how to handle this

**Comment by gswifort** [comment]
https://learn.microsoft.com/en-us/answers/questions/1304317/is-it-possible-to-get-a-reference-to-a-specific-in

**Comment by gswifort** [comment]
This should be helpful:

https://help.autodesk.com/view/OARX/2025/ENU/?guid=GUID-5D3C2397-B21D-4533-A9DF-BD21BA81758B

https://help.autodesk.com/view/OARX/2025/ENU/?guid=GUID-FE2E87F3-F537-471D-BF6A-B3A79CBF84B2

https://help.autodesk.com/view/OARX/2025/ENU/?guid=GUID-4558026D-4858-45C8-BC0F-6C323577BD45

**Comment by CEXT-Dan** [comment]
Thanks, I'll look at those. I was hoping to find a solution from the python side, in win32com. On of my thoughts is people could use the com wrappers as a replacement for pyautocad, run them out of process without the C++ side.

**Comment by gswifort** [comment]
Finding a solution in win32com will be harder, if not impossible. I've already looked for a solution to this problem before when I was automating work using COM, before your project (many thanks here! it makes me sick when I think about automating via COM).

**Comment by CEXT-Dan** [comment]
Okay, I'll look to see if I can pass something back from C++. I don't want to add a dependency to win32com, I also want to continue using the win32com generated wrappers, might be tricky

**Comment by CEXT-Dan** [comment]
I was able to get this to work on my machine with acadGetIDispatch, give it whirl when you have a chance

```Python
def getApp() -> IAcadApplication:
    iptr = Ap.Application.acadGetIDispatch()
    punk = pythoncom.ObjectFromAddress(iptr,pythoncom.IID_IDispatch)
    return win32com.client.Dispatch(punk, resultCLSID=AcadApplication.CLSID)
```

**Comment by gswifort** [comment]
Yes, it works!
