### ISSUE TITLE
BRX: Implement Civil Label Styles

### ISSUE THREAD

**Issue by schoeller** [CEXT-Dan/PyRx#119]
Hi Dan,

with SR166529 SR175732 in 25.1.05 the following changes have been introduced

> ".NET
> Implemented classes to facilitate the creation and manipulation of Civil Label Styles.
> SR166529 SR175732"

> "BRX/LISP
> The BrxCvDbPoint (C++) and Civil.Point (.NET) classes have been extended with a new static method assignPointToPointGroup().
> We introduced new classes for creation and manipulation of Civil Label Styles.
> SR166529 SR175732"

Sample
```
    //eug, create a symbol style
    {
        AcDbObjectId symbolStyleManagerId;
        BrxCvDbSymbolStyleManager::getManager(symbolStyleManagerId, acdbCurDwg(), true);
        AcDbObjectPointer<BrxCvDbSymbolStyleManager> symbolStyleManager(symbolStyleManagerId);
        if (symbolStyleManager == nullptr)
        {
            acutPrintf(_T("\n => Err: symbolStyleManager == nullptr")); // eug
            return;
        }
        AcDbObjectId symbolStyleId = symbolStyleManager->createSymbolStyle(_T("SR175732_SymbolStyle1"));
    }
    //eug, create a label style
    {
        AcDbObjectId pointLabelStyleManagerId;
        BrxCvDbPointLabelStyleManager::getManager(pointLabelStyleManagerId, acdbCurDwg(), true);
        AcDbObjectPointer<BrxCvDbPointLabelStyleManager> labelStyleManager(pointLabelStyleManagerId);
        if (labelStyleManager == nullptr)
        {
            acutPrintf(_T("\n => Err: labelStyleManager == nullptr")); // eug
            return;
        }
        AcDbObjectId labelStyle1Id = labelStyleManager->createLabelStyle(_T("SR175732_labelStyle1"));//OK
    }
```

Path in BRX SDK
`BRX25.1.05.0\inc\BrxSpecific\civil\`

Please consider implementing the changes.

Best regards

Sebastian

**Comment by CEXT-Dan** [comment]
I noticed that changes, I plan on making the updates

**Comment by CEXT-Dan** [comment]
Waiting for a v25 developer’s package from Bricsys before I can start. (can’t launch BricsCAD to test).
I’m guessing they’re overloaded with all the new orders.

**Comment by schoeller** [comment]
Tried to compile [PyRx.sln](https://github.com/CEXT-Dan/PyRx/blob/main/PyRx.sln) over the weekend in particular PyRxV25.0. I was intrigued that I might figure out how to contribute stubs. After altering some paths to BRXSDK I thought to be lucky, but later noticed that the BRX-file did not load. Banging my head...

**Comment by CEXT-Dan** [comment]
It’s a bit difficult to get setup, you might open up a discussion and I’ll help you through where you're stuck. I’m sure it will help other’s that follow

**Comment by schoeller** [comment]
> I noticed that changes, I plan on making the updates

Trying to get my head around stub files (no coding knowledge). Have assembled a table with files as in SDK 24.02 and 25.01 and compared to [PyRx/PyRxCore](https://github.com/CEXT-Dan/PyRx/tree/53c86f3fd712a92886d21e9c8ebd4cd506e36583/PyRxCore). Table looks as follows:

<img src="https://github.com/user-attachments/assets/2ee26665-f0d2-4d60-92f9-cb01dc33c730" width=600>

Apparently 1) there are changes in file structure between 24.02 and 25.01. Also 2) there is no name matching between 24.02 and PyRx. My (zero background) approach would be to pass file by file from SDK 25.01 to AI and punch in the return into `PyRx/PyRxCore/PyBrx<SDK-filename>` with one header file only and see where that leads me. 

Then again above approach does not differentiate between SDK-versions...

**Comment by CEXT-Dan** [comment]
Typically, I don’t exactly follow the exact file.h / file.cpp layout as the SDKs, they are all different between them, and I also want to minimize the number of files.  I usually name a file based off the base object and then just work down the class hierarchy. I usually begin to add new files with the hierarchy branches 

One way of checking if something has been implemented, or to find a class, is to look on the module's .cpp file.
For example, PyBrxCv.cpp contains a list of all the class wrappers, so if it’s not there, it’s not exposed to python. 
I also try to put all the enums in the module file 

```C++
BOOST_PYTHON_MODULE(PyBrxCv)
{
// all make defs go here
};
```

**Comment by CEXT-Dan** [comment]
Seems Bricsys does not want to support me on this project.  Closing until something changes

**Comment by schoeller** [comment]
> Seems Bricsys does not want to support me on this project. Closing until something changes

What a waste

**Comment by schoeller** [comment]
> Typically, I don’t exactly follow the exact file.h / file.cpp layout as the SDKs, they are all different between them, and I also want to minimize the number of files. I usually name a file based off the base object and then just work down the class hierarchy. I usually begin to add new files with the hierarchy branches
> 
> One way of checking if something has been implemented, or to find a class, is to look on the module's .cpp file. For example, PyBrxCv.cpp contains a list of all the class wrappers, so if it’s not there, it’s not exposed to python. I also try to put all the enums in the module file
> 
> ```c++
> BOOST_PYTHON_MODULE(PyBrxCv)
> {
> // all make defs go here
> };
> ```

Trying this steep learning curve (might be too steep for me). Have to take it step by step, since c++ is _zeropatatero_. Class reference is [available online](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_style.html). Started out like this in a newly created `PyRxCore\PyBrxCvLabel.h`:

```c++
#pragma once

#ifdef BRXAPP
#include "PyBrxCvObject.h"
#include "BrxCvDbObject.h"
#include "BrxCvDbStyle.h"

//-----------------------------------------------------------------------------------
//PyBrxCvDbStyle
void makePyBrxCvDbStyleWrapper();

class PyBrxCvDbStyle : public PyBrxCvDbObject
{
    using DisplayOrientation = BrxCvDbStyle::DisplayOrientation;
    using ScalingType = BrxCvDbStyle::ScalingType;
    using OrientationRef = BrxCvDbStyle::OrientationRef;
public:
    PyBrxCvDbStyle();
    PyBrxCvDbStyle(const PyDbObjectId& id);
    PyBrxCvDbStyle(PyBrxCvDbStyle* ptr, bool autoDelete);
    virtual ~PyBrxCvDbStyle() override = default;

    BrxCvDbStylePartDisplaySettingsPtrArray displaySettings(DisplayOrientation orientation) const;
    BrxCvDbStylePartDisplaySettingsPtr displaySetting(DisplayOrientation orientation, const AcString& partName) const;

    AcDbDate createdDate() const;
    AcString createdBy() const;

    AcDbDate lastEditedDate() const;
    AcString lastEditedBy() const;

    Acad::ErrorStatus setCreatedBy(const AcString& value);

public:
    inline PyBrxCvDbStyle* impObj(const std::source_location& src = std::source_location::current()) const;

};

};

#endif//BRXAPP

```

My understanding is that PyRx creates a class model from pre-defined objects and then defines the boost calls on top in the *.cpp file. So steps are as follows:

1. Derive class from base class. Since `PyBrxCvDbObject` is already defined from `BrxCvDbObject` we may use that accordingly.
`class PyBrxCvDbStyle : public PyBrxCvDbObject`

2. Define public types as a derivative of the base class BrxCvDbObject
`using DisplayOrientation = BrxCvDbStyle::DisplayOrientation;`

3. Declare public interface
```
PyBrxCvDbStyle();
PyBrxCvDbStyle(const PyDbObjectId& id);
PyBrxCvDbStyle(PyBrxCvDbStyle* ptr, bool autoDelete);
virtual ~PyBrxCvDbStyle() override = default;
```

4. Declare member functions
`BrxCvDbStylePartDisplaySettingsPtrArray displaySettings(DisplayOrientation orientation) const;`

5. Declare class explicitly to [be inline](https://en.cppreference.com/w/cpp/language/inline). Suppose this means to reside within the class hierarchy and has to be carried out for *all* derived classes.
`inline PyBrxCvDbStyle* impObj(const std::source_location& src = std::source_location::current()) const;`

**Comment by CEXT-Dan** [comment]
Basically, the classes do two things
1, right, you can use the basic outline from the base classes.  

2, I may have used the "using" statements for brevity, what’s important is that enums are also exported, I usually add them in the module cpp, I.e. PyBrxCv.cpp

3, right!

4, the member functions serve as tools for converting arguments and return types to types python can see. Python does not know what a BrxCvDbStylePartDisplaySettingsPtrArray is, so that will need to be converted to a boost::python::list. 
AcString will need to be a std::string for. 
AcDbDate will need to be a PyDbDate
Acad::ErrorStatus will need to be void, use PyThrowBadEs in the function body

5, the inline keyword in this case is used as an optimization hint, basically, it’s asking the compiler to copy/paste that section of code into the function body

BTW, appreciate the help!

**Comment by CEXT-Dan** [comment]
Thank you for your contribution! 
I added CvDbStylePartDisplaySettings and entries in CvDbStyleManager. 
I have no way of testing or generating stubs

If you can update your repository, make a fresh **debug** build, load the debug build into BricsCAD. 
You should see something like this.

![cmd](https://github.com/user-attachments/assets/e67726af-61b5-44ac-a148-d08906fce194)

If you do, run the command PYGENPYI, commit the newly generated PyBrxCv.pyi.
You may want to revert all the other PYI files. I will include PyBrxCv.pyi. in the next release

**Comment by schoeller** [comment]
> Thank you for your contribution! I added CvDbStylePartDisplaySettings and entries in CvDbStyleManager. I have no way of testing or generating stubs

Sponsored license required?

> If you do, run the command PYGENPYI, commit the newly generated PyBrxCv.pyi. You may want to revert all the other PYI files. I will include PyBrxCv.pyi. in the next release

Loaded the fresh compile successfully

<img src="https://github.com/user-attachments/assets/2ffaa42e-6678-41d3-9309-b1e4100d393a" width=480>

But no command return as indicated

**Comment by CEXT-Dan** [comment]
>Sponsored license required?
Any v25 key

>Loaded the fresh compile successfully
the one to load is 'PyRxGit\Bin\PyRx25.0\x64\Debug
you must load it from that folder as it uses relative paths to the utilities 

![debug](https://github.com/user-attachments/assets/f433dbf9-197a-43f2-92f4-6309c620d0e2)
![debug2](https://github.com/user-attachments/assets/7e8ab28e-9a25-41f2-a553-1970be5a1f10)

**Comment by CEXT-Dan** [comment]
I requested again, they’re probably busy with the more important clients  : )

**Comment by schoeller** [comment]
> I requested again, they’re probably busy with the more important clients : )

What's more important than innovation?

Will try to work myself now downwards

1. [BrxCvDbLabelStyleComponent](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_component.html)
2. [BrxCvDbLabelStyleArrow](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_arrow.html)
3. [BrxCvDbLabelStyleBlock](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_block.html)
4. [BrxCvDbLabelStyleLine](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_line.html)
5. [BrxCvDbLabelStyleText](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_text.html)

Likely to have missed something. Please bare in mind, that one cannot rely on my capabilites as per coding competence. I engage as per time available.

**Comment by CEXT-Dan** [comment]
you’ll be a C++ developer in no time :)

**Comment by CEXT-Dan** [comment]
> I requested again, they’re probably busy with the more important clients : )

success this time :)

**Comment by CEXT-Dan** [comment]
I plan to remove the ‘inline’ keyword from impObj functions. I started getting link errors with the latest VS Update. 
Compiler should automatically find these in release builds since I have this feature turned on . I don't care in debug

**Comment by schoeller** [comment]
> > I requested again, they’re probably busy with the more important clients : )
> 
> What's more important than innovation?
> 
> Will try to work myself now downwards
> 
>     1. [BrxCvDbLabelStyleComponent](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_component.html)
> 
>     2. [BrxCvDbLabelStyleArrow](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_arrow.html)
> 
>     3. [BrxCvDbLabelStyleBlock](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_block.html)
> 
>     4. [BrxCvDbLabelStyleLine](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_line.html)
> 
>     5. [BrxCvDbLabelStyleText](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_text.html)
> 
> 
> Likely to have missed something. Please bare in mind, that one cannot rely on my capabilites as per coding competence. I engage as per time available.

Ups, it seems I missed `BrxCvDbLabelStyle`.

**Comment by schoeller** [comment]
From my reading it seems that calling labelstyle from civil points is not possible, since the methods [StyleExtension.GetCivilPointLabelStyleManager](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_text.html) does not seem to be exposed (at least I cannot find it in the SDK). So the [sample file](https://github.com/CEXT-Dan/PyRx/blob/0248a0c70db803b13e443a61bed82cb030a9a76a/unitTests/testmedia/BCADCIVIL1.dwg) is of no use currently, unless one manages some other way

**Comment by CEXT-Dan** [comment]
getting closer, still missing 
BrxCvDbLineLabelStyleManager
BrxCvDbCurveLabelStyleManager
BrxCvDbPointLabelStyleManager
BrxCvDbSurfaceContourLabelStyleManager
BrxCvDbSurfaceSlopeLabelStyleManager
BrxCvDbSurfaceElevationLabelStyleManager

maybe PyBrxCvDbSymbolStyleManager will for all of them. it's quite confusing the way it was written as a C++ template

```Python
import traceback
from pyrx_imp import Rx, Ge, Gi, Db, Ap, Ed, Br, Cv

def PyRxCmd_sel1() -> None:
    try:
        ps, id, _ = Ed.Editor.entSel("\nPick: ", Cv.CvDbPoint.desc())
        cpnt = Cv.CvDbPoint(id)
        style = Cv.CvDbLabelStyle(cpnt.labelId())
        print(style.expressionCount())
    except Exception as err:
        traceback.print_exception(err)

def PyRxCmd_sym1() -> None:
    try:
        db = Db.curDb()
        styleid = Cv.CvDbSymbolStyleManager.getManagerId(db)
        manager = Cv.CvDbSymbolStyleManager(styleid,Db.OpenMode.kForWrite)
        newid = manager.createSymbolStyle("SR175732_SymbolStyle1")
        style = Cv.CvDbStyle(newid)
        print(style.lastEditedBy())
    except Exception as err:
        traceback.print_exception(err)
```

**Comment by schoeller** [comment]
> BrxCvDbLineLabelStyleManager
> BrxCvDbCurveLabelStyleManager
> BrxCvDbPointLabelStyleManager
> BrxCvDbSurfaceContourLabelStyleManager
> BrxCvDbSurfaceSlopeLabelStyleManager
> BrxCvDbSurfaceElevationLabelStyleManager

I have not done `BrxCvDbStyleManager.h` yet which contains 

`BrxCvDbStyleManager `-> `BrxCvDbStyleManagerT`
`BrxCvDbStyleManagerT `-> `BrxCvDbSurfaceElevationLabelStyleManager`

etc.

It seems that there were changes in

```
v24: BrxSpecific/civil/BrxCvDbObjectManager.h
v25: BrxSpecific/civil/BrxCvDbObjectManager.h
```

**Comment by CEXT-Dan** [comment]
I added them

**Comment by CEXT-Dan** [comment]
```Python
def PyRxCmd_doit1() -> None:
    try:
        db = Db.curDb()
        styleid = Cv.CvDbSymbolStyleManager.getManagerId(db)
        manager = Cv.CvDbSymbolStyleManager(styleid,Db.OpenMode.kForWrite)
        newid = manager.createSymbolStyle("SR175732_SymbolStyle1")
        ps, id, _ = Ed.Editor.entSel("\nPick: ", Cv.CvDbPoint.desc())
        cpnt = Cv.CvDbPoint(id,Db.OpenMode.ForWrite)
        cpnt.setSymbolId(newid)
    except Exception as err:
        traceback.print_exception(err)
```
![pntstyle](https://github.com/user-attachments/assets/a87258ad-9bf2-47ac-9daf-7599383767c0)

**Comment by CEXT-Dan** [comment]
this seems to work, but the label is not setup

```Python
def PyRxCmd_doit2() -> None:
    try:
        db = Db.curDb()
        styleid = Cv.CvDbPointLabelStyleManager.getManagerId(db)
        manager = Cv.CvDbPointLabelStyleManager(styleid,Db.OpenMode.kForWrite)
        newid = manager.createLabelStyle("SR175732_LaybeStyle1")
        ps, id, _ = Ed.Editor.entSel("\nPick: ", Cv.CvDbPoint.desc())
        cpnt = Cv.CvDbPoint(id,Db.OpenMode.ForWrite)
        cpnt.setLabelId(newid)
    except Exception as err:
        traceback.print_exception(err)
```

**Comment by schoeller** [comment]
> ```python
>         newid = manager.createLabelStyle("SR175732_LaybeStyle1")
> ```

Label style is available in settings afterwards, but requires addition of components in order to show info. Components are for example [CvDbLabelStyleText](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_text.html). No idea how to set up and attach a component to a label.

<img src="https://github.com/user-attachments/assets/d99578f7-4db6-4bd4-930b-c72ae012ac30" width=400>

**Comment by schoeller** [comment]
When doing this

```python
lab = Cv.CvDbLabelStyle(newid)
lab_c = Cv.CvDbLabelStyleText
cmtps = list()
cmtps.append(lab_c)
lab.addComponent(cmtps)
```

I receive

```
    lab.addComponent(cmtps)
Boost.Python.ArgumentError: Python argument types in
    CvDbLabelStyle.addComponent(CvDbLabelStyle, list)
did not match C++ signature:
    addComponent(class PyBrxCvDbLabelStyle {lvalue}, class PyBrxCvDbLabelStyleComponent)
```

Maybe some mismatch between [here](https://github.com/CEXT-Dan/PyRx/blob/e696345086f44700cf4eca6118ec1b70df3e09e2/PyRxCore/PyBrxCvDbLabel.h#L131) and [there](https://github.com/CEXT-Dan/PyRx/blob/e696345086f44700cf4eca6118ec1b70df3e09e2/PyRxCore/PyBrxCvDbLabel.cpp#L319) and [there](https://github.com/CEXT-Dan/PyRx/blob/e696345086f44700cf4eca6118ec1b70df3e09e2/PyRxCore/PyBrxCvDbLabel.cpp#L460)?

In the original header file it reads

`Acad::ErrorStatus addComponent(BrxCvDbLabelStyleComponentPtr pComponent);`

**Comment by CEXT-Dan** [comment]
Hi, I missed some constructors, PyBrxCvDbLabelStyle::addComponent also crashed
You will need to update your repository and build. give this a whirl

```Python
import traceback
from pyrx_imp import Rx, Ge, Gi, Db, Ap, Ed, Br, Cv

def PyRxCmd_doit1() -> None:
    try:
        db = Db.curDb()
        
        #create a style
        styleid = Cv.CvDbPointLabelStyleManager.getManagerId(db)
        manager = Cv.CvDbPointLabelStyleManager(styleid,Db.OpenMode.kForWrite)
        newid = manager.createLabelStyle("SR175732_LaybeStyle1")
        style = Cv.CvDbLabelStyle(newid,Db.OpenMode.kForWrite)
        
        #create a style componant and add it to the style
        lableStyleText = Cv.CvDbLabelStyleText()
        lableStyleText.setContents("hello world")
        lableStyleText.setTextAngle(45)
        style.addComponent(lableStyleText)
        
        #create a point and add the new style
        pnt = Cv.CvDbPoint()
        pnt.setPosition(Ge.Point3d(0,0,0))
        db.addToModelspace(pnt)
        pnt.setLabelId(newid)

    except Exception as err:
        traceback.print_exception(err)
```

**Comment by CEXT-Dan** [comment]
I found I still need to add type information to we can find the component types I.e.
```C++
        auto [ps, id, pnt] = entsel();
        AcDbObjectPointer<BrxCvDbPoint> dbpnt(id);
        AcDbObjectPointer<BrxCvDbLabelStyle> style(dbpnt->labelId());
        if ( !(style->componentCount() > 0))
            return;

        auto item = style->componentAt(0);
        bool isa =item->isA() == BrxCvDbLabelStyleText::desc();//isa
        acutPrintf(_T("\nname = %ls, isA = %ls "), item->isA()->name(), isa ? _T("True") : _T("False"));

        bool isDerivedFrom = item->isA()->isDerivedFrom(BrxCvDbLabelStyleText::desc());//isDerivedFrom
        acutPrintf(_T("\nname = %ls, isDerivedFrom = %ls "), item->isA()->name(), isDerivedFrom ? _T("True") : _T("False"));
```

**Comment by CEXT-Dan** [comment]
here's a sample getting a style (requires a new build)

```Python
import traceback
from pyrx_imp import Rx, Ge, Gi, Db, Ap, Ed, Br, Cv

#get contents from style assigned to point
def PyRxCmd_doit1() -> None:
    try:
        ps,id,_ = Ed.Editor.entSel("\nSelect: ", Cv.CvDbPoint.desc())
        pnt = Cv.CvDbPoint(id)
        style = Cv.CvDbLabelStyle(pnt.labelId())
        
        for item in style.components():
            if not item.isA() == Cv.CvDbLabelStyleText.desc():
                continue
            st = Cv.CvDbLabelStyleText.cast(item)
            print(st.contents())
            
    except Exception as err:
        traceback.print_exception(err)
```

**Comment by schoeller** [comment]
> ```python
>         styleid = Cv.CvDbPointLabelStyleManager.getManagerId(db)
>         manager = Cv.CvDbPointLabelStyleManager(styleid,Db.OpenMode.kForWrite)
>         newid = manager.createLabelStyle("SR175732_LaybeStyle1")
>         style = Cv.CvDbLabelStyle(newid,Db.OpenMode.kForWrite)
> ```

works flawlessly. When doing

```python
#create a style
styleid = Cv.CvDbSymbolStyleManager.getManagerId(db)
manager = Cv.CvDbSymbolStyleManager(styleid,Db.OpenMode.kForWrite)
newid = manager.createSymbolStyle("SR175732_LaybeStyle2")
style = Cv.CvDbLabelStyle(newid,Db.OpenMode.kForWrite)
```

it throws

```
PyRxCmd_doit4
    style = Cv.CvDbLabelStyle(newid,Db.OpenMode.kForWrite)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PyDb.ErrorStatusException: Exception!(eNotThatKindOfClass), function openAcDbObject, Line 67, File PyDbObjectId.h:
```

`CvDbLineLabelStyleManager` passes.
`CvDbCurveLabelStyleManager` passes.
`CvDbSurfaceSlopeLabelStyleManager` passes.
`CvDbSurfaceContourLabelStyleManager` passes.
`CvDbSurfaceElevationLabelStyleManager` passes.

**Comment by CEXT-Dan** [comment]
is BrxCvDbSymbolStyle class missing?

**Comment by schoeller** [comment]
> I don't see it. I'll add it

Sorry for leaving it out. It hides in `BrxCvDbSymbolStyle.h`.

**Comment by CEXT-Dan** [comment]
No worries. here's a sample

```Python
def PyRxCmd_doit4() -> None:
    try:
        db = Db.curDb()
        
        styleid = Cv.CvDbSymbolStyleManager.getManagerId(db)
        manager = Cv.CvDbSymbolStyleManager(styleid,Db.OpenMode.kForWrite)
        newid = manager.createSymbolStyle("MySymbolStyle")
        style = Cv.CvDbSymbolStyle(newid,Db.OpenMode.kForWrite)
        style.setCreatedBy("ItsAlive")
        style.setSquareFrame(True)
        print(style.createdBy())
        
        pnt = Cv.CvDbPoint()
        pnt.setSymbolId(newid)
        db.addToModelspace(pnt)
    except Exception as err:
        traceback.print_exception(err)
```

**Comment by CEXT-Dan** [comment]
Redundant. Generally iterator classes are redundant if their sole purpose is to iterate, I’d rather see toList() where applicable. I.e. I did not write wrappers for AcDbBlockTableIterator.  It makes it harder to manage memory 

I’m forced to write iterators for AcBrep as they seem to be an integral part of traversing objects

**Comment by CEXT-Dan** [comment]
I also added a toDict() method to help iteration or search in a more python way.
I plan to write more unit tests and publish a release towards the end of the week

**Comment by CEXT-Dan** [comment]
still todo
>BrxCvDbPoint classes have been extended with new static methods importPointsFromFile(), assignPointsToPointGroup(), and assignStylesToPoints().

**Comment by schoeller** [comment]
> still todo

Is there anything more to contribute from my side?

**Comment by CEXT-Dan** [comment]
I think it’s mostly done, we can root out individual items as they arise. 
Thank you!

**Comment by schoeller** [comment]
Trying to take steps with `CvDbLabelStyles` and stalled when trying to add components to the lot. 

This is where I start out with:

```python
def apply_line_label_style(manager: Cv.CvDbLineLabelStyleManager, config: dict, text_style_table: Db.TextStyleTable):
    """Apply a line label style configuration using the text style table."""
    new_id = manager.createLabelStyle(config["name"])
    style = Cv.CvDbLabelStyle(new_id, Db.OpenMode.kForWrite)
    style.setName(config["name"])
    style.setCreatedBy(config["created_by"])
    style.setDescription(config["description"])
    text_style_id = text_style_table.getAt(config["text_style_name"]) # Retrieve the text style by name from the text style table
    style.setTextStyle(text_style_id)
    style.setFlipAnchorsWithText(config["flip_anchors_with_text"])
```

When trying `style.addComponent` it wants a `Cv.CvDbLabelStyleComponent`, but I dunno how to create them. Have I missed a manager?

<img src="https://github.com/user-attachments/assets/8e7cdef7-03ef-4edc-96dd-af73e157605b" width=480>

Assistance kindly requested.

**Comment by CEXT-Dan** [comment]
Admittedly, I’m a bit lost since I’m not familiar with the API, or CV in general.  

From what I can see ```PyBrxCvDbLabelStyleComponent``` is a base class of 
```
PyBrxCvDbLabelStyleArrow
PyBrxCvDbLabelStyleBlock
PyBrxCvDbLabelStyleLine
PyBrxCvDbLabelStyleText
```


`PyBrxCvDbLabelStyleComponent `is abstract, so you have to use a derived class , maybe something like 

```
component = Cv.CvDbLabelStyleLine()
style.addComponent(component)
```
