### ISSUE TITLE
BRX: investigate BrxGenericPropertiesAccess

### ISSUE THREAD

**Issue by CEXT-Dan** [CEXT-Dan/PyRx#135]
>We implemented a new generic properties API to access any and all object properties from DWG database objects, including properties defined by BIM, MCAD, Civil, IFC, Point Cloud, and third party party OPM extensions. See header file BrxSpecific/BrxGenericPropertiesAccess.h for documentation.

**Comment by schoeller** [comment]
Cool! By the first looks I may contribute as for CvDbLabel based on [docs](https://developer.bricsys.com/bricscad/help/en_US/V25/DevRef/index.html?page=source%2Fclass_brx_cv_db_label_style_text.html) if of use.

**Comment by schoeller** [comment]
> Sure if you want to take a crack at it : )
> 
> Question, should there be another module since this is more generic than Civil, Bim or Mechanical? I can setup a new module PyBrx

Module independant of verticals would be logical. Contributions will be as for CvDbLabel, so you'll have to clean up my tweedy doing...

**Comment by CEXT-Dan** [comment]
I think maybe we are discussing something different?
this task is to look at what’s in BrxGenericPropertiesAccess.h. I only see a few generic functions 

BrxDbProperties:: listAll
BrxDbProperties:: isValid
BrxDbProperties:: isReadOnly
BrxDbProperties:: getValue
BrxDbProperties::setValue

This seems pretty valuable, not only for BricsCAD, but across all platforms. So the investigation is 
Is this possible to do across all platforms? Maybe if so, I can put BrxDbProperties in PyDb etc.

But then there’s other useful things in generic Brx, so maybe I should also create a PyBrx module

**Comment by schoeller** [comment]
> This seems pretty valuable, not only for BricsCAD, but across all platforms. So the investigation is Is this possible to do across all platforms? Maybe if so, I can put BrxDbProperties in PyDb etc.

I am not in a position to judge on this. From my point of view to an end user PyRx must always deliver stable results, thus if the possibility exists that functionality from BRXSDK mingles data within an ACAD installation (for example verticals as C3D) that must be avoided.

> But then there’s other useful things in generic Brx, so maybe I should also create a PyBrx module

As a user I have the need to sync attribute/properties across vertical products. For example piping diameter used in BCAD mechanical is to be synced to a BCAD bim custom property field in order to be exported as IFC. Other than that I have no overview of what useful functionality is provided in generic Brx.

**Comment by CEXT-Dan** [comment]
sample
```
import traceback
from pyrx_imp import Rx, Ge, Gs, Gi, Db, Ap, Ed, Brx

def PyRxCmd_doit1():
    try:
        #circle
        ps, id, _ = Ed.Editor.entSel("\nSelect: ")
        vals = []
        for prop in Brx.DbProperties.listAll(id):
            isvalid, fqname = Brx.DbProperties.isValid(id,prop)
            
            if(isvalid):
                val = Brx.DbProperties.getValue(id,prop)
                vals.append((prop,val.dataType(),val.format()))
        print(vals)
        
    except Exception as err:
        traceback.print_exception(err)

def PyRxCmd_doit2():
    try:
        #circle
        ps, id, _ = Ed.Editor.entSel("\nSelect: ")
        diam = Db.AcValue(200.0)
        Brx.DbProperties.setValue(id,'Diameter~Native',diam)
    
    except Exception as err:
        traceback.print_exception(err)
```

**Comment by CEXT-Dan** [comment]
So a fully qualified name might look like Story~BIM , Layer~Native, SequenceNumber~BIM
It’s very specialized to BricsCAD. If I decide to do something with AutoCAD’s property manager, I will probably do it in PyDb

**Comment by schoeller** [comment]
This is top notch! I will try to stitch something with it. Thanks a ton for your knowledge!

**Comment by schoeller** [comment]
Pulled, compiled. When loading in V25.06 I get

```python
PyErr cannot import name 'Brx' from 'pyrx_imp' (C:\Users\Sebastian Schoeller\AppData\Local\Programs\PyRx\Stubs\pyrx_imp.py) ,Traceback - 
At <module> (C:\Users\Sebastian Schoeller\Nextcloud\10000-Beruf\02-Software\PyRx\Bim_AttSync.py:2): 
pyload failed: 
```

PyGenPy delivers:

```python
: PYGENPYI
19135
531
PyBrxBim::BimBuilding::allObjectBuildings
PyBrxBim::BimBuilding::allObjectStories
PyBrxBim::BimBuilding::allObjectStoriesFromDb
PyBrxBim::BimBuilding::allStringBuildings
PyBrxBim::BimBuilding::allStringStories
PyBrxBim::BimBuilding::allStringStoriesFromDb
PyBrxBim::BimBuilding::assignedObjects
PyBrxBim::BimClassification::getAllClassified
PyBrxBim::BimClassification::getAllClassifiedAs
PyBrxBim::BimClassification::getAllClassifiedAsName
PyBrxBim::BimClassification::getAllUnclassified
PyBrxBim::BimClassification::getAllUsedClassificationNames
PyBrxBim::BimClassification::getAllUsedClassifications
PyBrxBim::BimClassification::getBimTypeNames
PyBrxBim::BimClassification::getPropertyNames
PyBrxBim::BimRoom::getAllRoomsS
PyBrxBim::BimRoom::getBoundingElements
PyBrxBim::BimRoom::getBoundingElementsS
PyBrxBim::BimRoom::getOpenings
PyBrxBim::BimRoom::getOpeningsS
PyBrxBim::BimSpace::getAllSpaces
PyBrxBim::BimSpace::getAssignedEntities
PyBrxBim::BimSpace::getAssignedSpace
PyBrxBim::BimSpace::getBoundingElements
PyBrxBim::BimSpatialLocation::assignedObjects
PyBrxBim::BimStory::allStories
PyBrxBim::BimStory::allStoryNames
PyBrxBim::BimStory::assignedObjects
PyBrxBim::Core::findMatchingBlockDefinition
PyBrxBim::Core::findSimilar3dSolids
PyBrxBim::Core::findSimilarGeometry
PyBrxBim::Core::getAnchoredBlockReferences
PyBrxBim::Core::isSimilarGeometry
PyBrxBim::Core::matchEntitiesToBlockDefinitions
PyBrxBim::Core::replaceGeometryByBlocks
PyBrxBim::IfcEntity::getInverseRefs
PyBrxBim::IfcImportContext::createSweptArea
PyBrx::Core::getOpenObjects
PyBrx::DbProperties::isReadOnly
PyBrx::DbProperties::isValid
PyBrx::DbProperties::listAll
```

**Comment by CEXT-Dan** [comment]
it appears that the path is set to the last installation v1.3.039, instead of your development directory (Brx namespace hasn't been released yet)

I will make a new install so they are in sync

**Comment by CEXT-Dan** [comment]
oh, it was released 

pyrx_imp should look like this
```Python
import importlib.util
if importlib.util.find_spec("PyBrxCv") is not None:
    import PyBrxCv as Cv
    
if importlib.util.find_spec("PyBrxBim") is not None:
    import PyBrxBim as Bim
    
if importlib.util.find_spec("PyBrx") is not None:
    import PyBrx as Brx
```

**Comment by schoeller** [comment]
In VS I have in `.env`

`PYTHONPATH = "C:\Users\Sebastian Schoeller\Documents\GitHub\PyRx\PyRxStubs"`

in BCAD

`GITPATH=C:\Users\Sebastian Schoeller\Documents\GitHub\PyRx`


I still get

<img src="https://github.com/user-attachments/assets/730e69e7-478e-4dd0-915c-7f60e0d7fae9" width=480>

with PyRx compiled freshly and install folder set correctly

<img src="https://github.com/user-attachments/assets/e4d5475b-3bf4-4a31-a9fd-ff0695ed35df" width=600>

**Comment by CEXT-Dan** [comment]
That’s a PyLance warning, note the comment at the end of pyrx_imp

**Comment by CEXT-Dan** [comment]
I was looking for the brx line 
```Python
if importlib.util.find_spec("PyBrx") is not None:
    import PyBrx as Brx
```

**Comment by schoeller** [comment]
All working now. Thanks for the support. 
Filter definitions seems to be similar to typed plans in BCAD. Can't find any docs on it, but (cheers to you) have Python now ;-)

<img src="https://github.com/user-attachments/assets/4ca1146f-db9f-4085-9b66-757b9d91de4e" width=480>
