### ISSUE TITLE
Empty BlockReference.attributeIds()

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#2]
Hi, I have a problem with this example.  when I insert a block and want to change its attributes, I get an empty list.

https://github.com/CEXT-Dan/PyRx/blob/main/PySamples%2Finsertblock.py#L30-L32

```
blockRef = Db.BlockReference(Ge.Point3d(100,100,0),blockId)
model = Db.BlockTableRecord(db.modelSpaceId(), Db.OpenMode.kForWrite)
model.appendAcDbEntity(blockRef)
attrs = blockRef.attributeIds()  # empty
```

**Comment by CEXT-Dan** [comment]
Hi, Since AttributeReferences are owned by the BlockReference, you must add them to the with
Db.BlockReference.appendAttribute. 

I’ve added a sample block with attributes and updated the sample, I hope this will better illustrate this
~Dan

**Comment by CEXT-Dan** [comment]
As a side note, I’ve added a set of ActiveX wrappers, (not 100% tested), these wrappers are different than PyAutoCAD in that all function arguments should accept python types, you should not have to use Variants. 

Its should be ok to mix ActiveX and Native wrappers, you may have to watch the object open state 
 
example
<pre>
import traceback
import PyRx as Rx
import PyGe as Ge
import PyGi as Gi
import PyDb as Db
import PyAp as Ap
import PyEd as Ed

#ActiveX this is an app specific import 
import AxApp24 as Ax

def PyRxCmd_doit() -> None:
    try:
        ptres = Ed.Editor.getPoint("\nSpecify insertion point: ")
        if(ptres[0] != Ed.PromptStatus.eOk):
            print("Oops!: ", ptres[0])
            return
        
        path = "M:\\Dev\\Projects\\PyRxGit\\PySamples\\dwg\\GRA.dwg"
        
        db = Db.HostApplicationServices().workingDatabase()
        block = Db.Database(False, True)
        block.readDwgFile(path)
        block.closeInput(True)
        
        # maybe you want to modify the block before inserting it
        # add an attribute, entities or move stuff around 
        blockId = Db.ObjectId()
        db.insert(blockId, "GRA", block, True)
        
        #ActiveX
        axapp = Ax.getApp()
        ref = axapp.ActiveDocument.ModelSpace.InsertBlock(ptres[1].toTuple(),'GRA', 1,1,1,0,'')
       
        refId = Db.ObjectId()
        refId.setFromOldId(ref.ObjectID)
        
        # back to native
        ref = Db.BlockReference(refId)
        attrefs = [Db.AttributeReference(id) for id in ref.attributeIds()]
        for attref in attrefs:
            print(attref.tag(), attref.textString())

    except Exception as err:
        traceback.print_exception(err)
</pre>

**Comment by gswifort** [comment]
Thanks !
I used ActiveX (via COM) before I discovered your project, but it is much slower. Adding AttributeReferences does the trick.

**Comment by CEXT-Dan** [comment]
Great, glad it works!
FYI, AxApp24 COM wrappers are very fast, they are early bound and executed inside the AutoCAD process. I benched it about 140x faster than pyautocad. Nothing against pyautocad, it’s run out of process, excruciatingly slow. 
Of course ARX wrappers are much cooler : )
Closing this
