### ISSUE TITLE
PYRELOAD reloading modules

### ISSUE THREAD

**Issue by schoeller** [CEXT-Dan/PyRx#26]
Dear all,

thx for this opensource. 
A central script commands.py is calling a as follows

1#commands.py:
`from pybrxcv.samples import AlignmentSample`

2#pybrxcv/samples/AlignmentSample.py
`from ..utils import cvdbalignment`

3#pybrxcv/utils/cvdbalignment.py
`def cvDbHAlignment_iter(objId)`

When modifyng script 2# and reloading script 1#, currently script 2# does not seem to be reloaded. I have to restart my BCAD to take effect. 

Would it be possible to reload all modified modules?

Best

Sebastian

**Comment by gswifort** [comment]
That's true, that would be helpful. You can check which modules have changed based on their hash.

**Comment by gswifort** [comment]
There is probably no need to check whether built-in modules have changed. An additional `reload_all` function can be added.

**Comment by CEXT-Dan** [comment]
it is annoying having to restart cad. I will investigate this

**Comment by CEXT-Dan** [comment]
Turns out this is not a trivial task. At least It’s not as simple as reloading all the referenced modules with importlib.reload(my_module)

1, reloading a module that has a command registered may crash AutoCAD, I store a pointer to functions so they can be called, if they are moved AutoCAD will crash

2, some modules way deep in the system are frozen causing python to throw an exception, so the reload fails

While I think on this, you can reload the modules using importlib.reload
It’s the same issue with my changes to the tests but I set it to reload the tests on OnPyInitApp, see UnitTestRunner.py

**Comment by CEXT-Dan** [comment]
An ideas is, I can add OnPyReload() pretty easily, this way it gives **you** control over what’s reloaded

**Comment by schoeller** [comment]
> That's true, that would be helpful. You can check which modules have changed based on their hash.

I tried what was working a script, but apparently not clever enoug. When calling detect_file_changes from within BCAD it crashes. 

```python
# https://www.geeksforgeeks.org/how-to-detect-file-changes-using-python/
import hashlib
import time
def calculate_file_hash(file_path):
    with open(file_path, "rb") as f:
        file_hash = hashlib.sha256(f.read()).hexdigest()
    return file_hash

# https://stackoverflow.com/questions/9727673/list-directory-tree-structure-in-python
def fs_tree_to_dict(path_):
    file_token = ''
    for root, dirs, files in os.walk(path_):
        tree = {d: fs_tree_to_dict(os.path.join(root, d)) for d in dirs}
        tree.update({f: calculate_file_hash(os.path.join(root, f)) for f in files})
#        tree.update({f: file_token for f in files})
        return tree

def detect_file_changes(file_path):
    last_hash = fs_tree_to_dict(file_path)
    while True:
        current_hash = fs_tree_to_dict(file_path)
        if current_hash != last_hash:
            print("Something has changed, reloading modules!")
#            reload_modules()
            last_hash = current_hash
        time.sleep(1)
```

**Comment by CEXT-Dan** [comment]
I added OnPyReload in 1.3.008, from there you can update other modules

I will add Ap.Application.reload() and other helper functions, I.e. return a list of modules that are loaded in C++
If the cache is invalidated on modules that have command pointers, the application will certainly crash

**Comment by schoeller** [comment]
@CEXT-Dan I binge whatever I tried. works like a charmer. Thx

**Comment by CEXT-Dan** [comment]
It’s great that there’s a python solution, I would except this would be the case.
There could be a python(s) command included in stubs.
I added some helper functions for determining what modules were loaded with pyload
and also Ap.Application::reloadPythonModule

 Closing this for now
