### ISSUE TITLE
Break from endless loop

### ISSUE THREAD

**Issue by schoeller** [CEXT-Dan/PyRx#27]
Thx for the work.

When (undesirably) ending in a wrongly defined loop like below:
```python
        while True:
            ssResult = Ed.Editor.getInteger("Set style(0 - off, 1 - triangles, 2 - contours and points) :")
            if ssResult[0] == Ed.PromptStatus.eNormal : 
                print(ssResult[1])
                if ssResult[0] in range(2):
                    break
```
I cannot exit from the BCAD command line nor BCAD itself. I suggest this should be possible.

**Comment by CEXT-Dan** [comment]
in your code break is never called in an error condition 

```python
while True:
            ssResult = Ed.Editor.getInteger("Set style(0 - off, 1 - triangles, 2 - contours and points) :")
            if ssResult[0] != Ed.PromptStatus.eNormal : 
                break
            print(ssResult[1])
```

**Comment by schoeller** [comment]
The sample code is erroneous. Below correction works. I just wondered whether one should be able to CTRL+C it from BCAD, or whether it is unreasonable to undertake the effort. I could neither stop VS Code, nor BCAD.

```python
        # get merge input as integer between 0-2
        while True:
            ssResult = Ed.Editor.getInteger("\n0 - merge to existing, 1 - create new surface")
            if ssResult[0] == Ed.PromptStatus.eNormal : 
                if ssResult[1] in range(2):
                    break
```

**Comment by CEXT-Dan** [comment]
there's a better approach than doing a while loop. There's an API to handle this for you 
Maybe PySamples/PyEd/InitGet.py will give you insperation
