### ISSUE TITLE
Clearing PyRxCmd on PYRELOAD

### ISSUE THREAD

**Issue by schoeller** [CEXT-Dan/PyRx#28]
Thx for this code.

A function `PyRxCmd_samp_tinmerg` has been created. Lateron is is being renamed to `PyRxCmd_samp_tinmerge`. After calling PYLOAD they both seem still to be visible from the command line in BCAD.

![grafik](https://github.com/CEXT-Dan/PyRx/assets/106036/49e831b8-fe7d-436c-a9df-6cecd7460afd)

**Comment by CEXT-Dan** [comment]
Yes, there are some limitations to using reload

https://docs.python.org/3/library/importlib.html#importlib.reload
>It is generally not very useful to reload built-in or dynamically loaded modules
>In many cases extension modules are not designed to be initialized more than once, and may fail in arbitrary ways when reloaded.

I added the reload command for development purposes. But as mentioned in the there are limitations 
It seems to do a good job reloading with small changes;  however, I’ve noticed sometimes python becomes unstable and throws an exception

I probably won’t go through to trouble of unregistering commands
