### ISSUE TITLE
Passing point list to drapePoint

### ISSUE THREAD

**Issue by schoeller** [CEXT-Dan/PyRx#29]
When calling `drapePoint` on a surface and passing a list of `Ge.Point3D` objects an error is thrown.

1# pts => list of Ge.Point3D objects
<img src=https://github.com/CEXT-Dan/PyRx/assets/106036/37755f69-1561-4c2a-95fd-ef740999a094 width=400>

2#
<img src=https://github.com/CEXT-Dan/PyRx/assets/106036/2eaf3104-2b95-46c8-9340-cd64bdb13aa2 width=400>

3#
```python
    dpts = pSurface.drapePoint(pts)
           ^^^^^^^^^^^^^^^^^^^^^^^^
Boost.Python.ArgumentError: Python argument types in
    CvDbTinSurface.drapePoint(CvDbTinSurface, list)
did not match C++ signature:
    drapePoint(class PyBrxCvDbTinSurface {lvalue}, class AcArray<class AcGePoint3d,class AcArrayMemCopyReallocator<class AcGePoint3d> >)
```

If not properly used, please kindly advise with an example.

**Comment by CEXT-Dan** [comment]
Hi, 
I see it's my bug

**Comment by schoeller** [comment]
Thx for committing. Trying PyRx version <1.3.009.20240807> in BCAD 24.2. I would expect a list with altered z-values only. Would you agree?

1#
```python
        pts=[]
        pts.append(Ge.Point3d(bbox[1][0],bbox[1][1],maxEle)) #xmax,ymax,zmax
        pts.append(Ge.Point3d(bbox[0][0],bbox[0][1],maxEle)) #xmin,ymin,zmax
        pts.append(Ge.Point3d(bbox[0][0]+10,bbox[0][1]+10,maxEle)) #xmin+10,ymin+10,zmax
        pts.append(Ge.Point3d(bbox[0][0]+10,(bbox[0][1]+bbox[1][1])/2,maxEle)) #xmin+10,(ymin+ymax)/2,zmax
        pts.append(Ge.Point3d(bbox[1][0],(bbox[0][1]+bbox[1][1])/2,maxEle)) #xmax,(ymin+ymax)/2,zmax
        dpts = pSurface.drapePoints(pts)
```

2#pts
`[<PyGe.Point3d(143.01495434908247,53.31370849898477,10.00000000000000)>, <PyGe.Point3d(1.59359811177296,-88.10764773832474,10.00000000000000)>, <PyGe.Point3d(11.59359811177296,-78.10764773832474,10.00000000000000)>, <PyGe.Point3d(11.59359811177296,-17.39696961966999,10.00000000000000)>, <PyGe.Point3d(143.01495434908247,-17.39696961966999,10.00000000000000)>]`

3#dpts
`[[<PyGe.Point3d(107.65961528975510,17.95836943965739,10.00000000000000)>, <PyGe.Point3d(84.08938925020351,-5.61185659989420,1.66666666666667)>, <PyGe.Point3d(79.37534404229319,-10.32590180780452,0.00000000000000)>, <PyGe.Point3d(72.30427623042772,-17.39696961966999,0.00000000000000)>, <PyGe.Point3d(65.23320841856224,-24.46803743153547,0.00000000000000)>, <PyGe.Point3d(60.51916321065193,-29.18208263944579,1.66666666666667)>, <PyGe.Point3d(36.94893717110034,-52.75230867899737,10.00000000000000)>], [<PyGe.Point3d(11.59359811177296,-27.39696961967000,10.00000000000000)>, <PyGe.Point3d(11.59359811177296,-17.39696961966999,8.23223304703363)>, <PyGe.Point3d(58.16214060669677,-17.39696961966999,0.00000000000000)>, <PyGe.Point3d(72.30427623042772,-17.39696961966999,0.00000000000000)>, <PyGe.Point3d(86.44641185415867,-17.39696961966999,0.00000000000000)>, <PyGe.Point3d(143.01495434908247,-17.39696961966999,10.00000000000000)>]]`

**Comment by CEXT-Dan** [comment]
I don’t know the design, at first, I thought it should be the same as the tinproject command, but after reading the comments, I’m unsure the intent

// drapes the TinSurface using the provided 'points', returns an array of curves
// (each array can be used to create an AcDb3dPolyline)

3900 input
9413 output

So it’s doing something specific 

![drape](https://github.com/CEXT-Dan/PyRx/assets/26830697/4c289fec-706a-45ef-a8d6-541c9efa1387)

**Comment by schoeller** [comment]
should looked into the variables inspector first:
```python
        dpts = pSurface.drapePoints(pts)
        for i, dpt in enumerate(dpts):
            dline = Db.Polyline3d()
            dline.setColorIndex(3, True)
            for j in range(len(dpt)):
                dline.appendVertex(Db.Polyline3dVertex(dpt[j]))
            dlid = db.addToModelspace(dline)
```
