### ISSUE TITLE
Plug-In localization

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#37]
By default, the plug-in is installed in the global directory (for all users), an option to install it for the current user (changing the installation directory) would be useful.

1. Directory for global installation (currently): `%ALLUSERSPROFILE%\Autodesk\ApplicationPlugins`
2. "per-user" installation directory: `%APPDATA%\Autodesk\ApplicationPlugins`

[Autodesk doc](https://help.autodesk.com/view/ACDLT/2024/ENU/?guid=GUID-5E50A846-C80B-4FFD-8DD3-C20B22098008)

I moved the files manually to this directory (for the current user) and everything seems to work fine.

**Comment by CEXT-Dan** [comment]
Interesting, I can move it.
I just used the same setup as my apps in the Appstore.

**Comment by gswifort** [comment]
I think not to move it but to give a choice, something like this:

![image](https://github.com/CEXT-Dan/PyRx/assets/131259064/2058eb9b-feb3-47f8-b08e-8e3c8ad3c88a)

**Comment by CEXT-Dan** [comment]
I would rather not have the option. 
I have the installer setup InstallAllUsersVisible=FALSE and I already had deleted the radio button page. 
There were issues not being able to set user environment variables from the installer executable in all-users
Also, the stubs and everything else is in %APPDATA%, so it seems logical just to move it

**Comment by gswifort** [comment]
Right, in the case of `.msi` you would probably have to create two separate installers.
But for me the "per-user" option is enough.
