### ISSUE TITLE
Missing function mergeSurfaces

### ISSUE THREAD

**Issue by CEXT-Dan** [CEXT-Dan/PyRx#39]
Cheers. [Cannot see](https://github.com/CEXT-Dan/PyRx/blob/8767b69956526019f362a98888c7292ba6101f04/PyRx/PyBrxCvDbTinSurface.cpp#L894) it in the VS Code typing propositions 

<img src="https://github.com/CEXT-Dan/PyRx/assets/106036/7e9cd9ea-86f5-4dc3-8319-46011fb55a16" width=300>

Not working as follows:
```python
                    nSurface = Cv.CvDbTinSurface()
                    nSurface.mergeSurfaces(fSurface, sSurface)
```

_Originally posted by @schoeller in https://github.com/CEXT-Dan/PyRx/discussions/34#discussioncomment-9066534_

**Comment by CEXT-Dan** [comment]
this should work in v1.3.013

**Comment by schoeller** [comment]
Thx again for your work. Unfortunately I still have trouble making things work. Ideas very welcome.

1#I have attached a file with two TINs.

2#When calling below everything is fine
```python
            case 1:
                try:
                    nSurface = Cv.CvDbTinSurface()
                    nSurface.initialize(Ge.Point3d(0,0,0), Ge.Point3d(0,0,0), 2)
                    db.addToModelspace(nSurface)

```

3a#When adding subsequent code after `inititialize()` it fails
```python
                    nSurface.upgradeOpen()
                    nSurface = Cv.CvDbTinSurface().mergeSurfaces(fSurface, sSurface)
```

3b#When adding subsequent code instead it fails
```python
                    nSurface.mergeSurfaces(fSurface, sSurface)
```

4#Same when leaving out `initialize()`

[Zeichnung1.zip](https://github.com/CEXT-Dan/PyRx/files/14954178/Zeichnung1.zip)

**Comment by CEXT-Dan** [comment]
Hi, it should be a static method, something like 
nSurface = Cv.CvDbTinSurface.mergeSurfaces((fSurface, sSurface)

**Comment by CEXT-Dan** [comment]
```Python
import traceback
from pyrx_imp import Rx, Ge, Gi, Db, Ap, Ed, Cv

def PyRxCmd_doit():
    try:
        es1 = Ed.Editor.entSel("\nfirst: ")
        es2 = Ed.Editor.entSel("\nsecond: ")
        
        fSurface = Cv.CvDbTinSurface(es1[1])
        sSurface = Cv.CvDbTinSurface(es2[1])
        nSurface = Cv.CvDbTinSurface.mergeSurfaces(fSurface, sSurface)
        
        db = Db.curDb()
        print(db.addToModelspace(nSurface))
        
    except Exception as err:
        traceback.print_exception(err)
        
```

**Comment by schoeller** [comment]
Superb. I can confirm it work. Have to read up on _static method_. Cheers. Have thus managed to create a `split` TIN surface (which seems a little useless), but that's up to the editor.
<img src="https://github.com/CEXT-Dan/PyRx/assets/106036/7e205355-b030-4c50-9ac4-85236b84b2b7" width=360>
