### ISSUE TITLE
APPLOAD on ZWCAD doesn't work

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#53]
When I load PyRx on ZWCAD I get an error:
`> C:\Users\gswi\AppData\Local\Programs\PyRx\Bin\PyRxZ24.0.zrx The desired dynamic link for the library or other files could not be found.`
`> C:\Users\gswi\AppData\Local\Programs\PyRx\Bin\PyRxZ24.0.zrx were not loaded.`

**Comment by CEXT-Dan** [comment]
Hi, are you loading with RxLoaderZ24.0.zrx?
If so, please run this lisp at the prompt (setenv “PYRX_LOG” “1”) and post the results, it should be something like 

`
Command: 
M:\Dev\Projects\PyRxGit\Bin\PyRxZ24.0\x64\Debug\RxLoaderZ24.0.zrx load successfully!
Command: 
PyRxLoader::getPythonVenvPath 
PyRxLoader::thisModulePath M:\Dev\Projects\PyRxGit\Bin\PyRxZ24.0\x64\Debug\
PyRxLoader::getInstallPath C:\Users\Dan\AppData\Local\Programs\PyRx
PyRxLoader::getIniPath M:\Dev\Projects\PyRxGit\Bin\PyRxZ24.0\x64\Debug\PyRx.INI
PyRxLoader::validateINIPythonInstallPath c:\users\dan\appdata\local\programs\python\python312
PyRxLoader::validateINIwxPythonPath c:\users\dan\appdata\local\programs\python\python312\Lib\site-packages\wx
Loading PyRx from ini condition
PyRxLoader::PyRxLoader_loader Loading, M:\Dev\Projects\PyRxGit\Bin\PyRxZ24.0\x64\Debug\PyRxZ24.0.Zrx
Finished PyRxLoader_loader
PyRx version <1.3.017.20240508> loaded:
Python Interpreter Loaded successfully!
`

**Comment by gswifort** [comment]
My stupid mistake - I forgot to install python 3.12 (I had 3.11).

**Comment by CEXT-Dan** [comment]
ZRX is pretty good, but you may find some things are missing, if you run into exceptions post them and we’ll report them to ZDN
