### ISSUE TITLE
Support section entities

### ISSUE THREAD

**Issue by schoeller** [CEXT-Dan/PyRx#62]
Dear all,

thanks once more for everything.

I'd like to be able to create and configure a section entity (`_SECTIONPLANE`) in order to generate as below.

BCAD:
<img src=https://github.com/CEXT-Dan/PyRx/assets/106036/45fa0433-95a6-488d-bb0e-a00b252e29d8 width=480>

ACAD:
<img src=https://github.com/CEXT-Dan/PyRx/assets/106036/58e4455b-b1c7-4661-8a75-9c5242177ce1 width=480>

**Comment by CEXT-Dan** [comment]
Ok, I’ll add 
AcDbSection 
AcDbSectionManager
AcDbSectionSettings
AcDbSectionGeometryMap

It may take some time

**Comment by CEXT-Dan** [comment]
BricsCAD is missing functions, so functionality may be limited
```
enum Acad::ErrorStatus __cdecl AcDbSectionManager::getLiveSection(class AcDbObjectId &)const
enum Acad::ErrorStatus __cdecl AcDbSectionManager::getSection(wchar_t const *,class AcDbObjectId &)const
enum Acad::ErrorStatus __cdecl AcDbSectionManager::getUniqueSectionName(wchar_t const *,wchar_t * &)const
```

**Comment by CEXT-Dan** [comment]
think this is done

**Comment by schoeller** [comment]
> BricsCAD is missing functions, so functionality may be limited

Have you posted tickets for missing methods or should I do it?

**Comment by CEXT-Dan** [comment]
I have not filed an SR, because I have not seen a sample yet where the functions are needed.  
If you need them, please create an SR

**Comment by schoeller** [comment]
Out of curiosity is it possible to shape a section according to a GeCurve or DbCurve? Ifso, how would I do that?

**Comment by CEXT-Dan** [comment]
Never tried, my sample post @theswamp was the first time I ever created a Section : |
