### ISSUE TITLE
EditorReactor failed

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#64]
When I load [this module](https://github.com/CEXT-Dan/PyRx/blob/ec77d2fe200f9d9fd8be0ca698c804cb09ad07cb/PySamples/testEntityReactor.py) and call `pyregedreactor`, an `Unhandled Access Violation Reading (...)` exception is raised when copying an object using `Ctrl+C`. An exception is raised when leaving the `commandWillStart` method.

**Comment by CEXT-Dan** [comment]
Thanks for that! This should be fixed in v1.3.022 I just published

**Comment by CEXT-Dan** [comment]
should be fixed
