### ISSUE TITLE
No getIterator method in Db.Table?

### ISSUE THREAD

**Issue by kwollaston** [CEXT-Dan/PyRx#76]
From testDbTable.py:

```
table = Db.Table(es[1])
for cell in table.getIterator(Db.CellRange(1,0,3,3)):
    print(table.textString(cell))
```

I am getting an error saying table has no method getIterator. 

I see it in the AutoCAD docs here: https://help.autodesk.com/view/OARX/2023/ENU/?guid=OARX-RefGuide-__OVERLOADED_getIterator_AcDbTable

I am using AutoCAD 2025

**Comment by CEXT-Dan** [comment]
Sorry about that, table.getIterator didn’t really seem appropriate, so I renamed it to table.cells, this won’t change.

```Python
        table = Db.Table(es[1])
        for cell in table.cells(Db.CellRange(1,0,3,3)):
            print(table.textString(cell))
```

There’s also table.cellValues, a list of tuples (nRow, nCol, strValue) 
But this may change, instead of strValue, I want to unpack the value while maintaining the type 

```
        table = Db.Table(es[1])
        for cv in table.cellValues(Db.CellRange(1,0,3,3)):
            print(cv)
```
IMHO, tables could be made better, but I won’t go around renaming functions now that people are using them lol

**Comment by gswifort** [comment]
Maybe it's best to add an alias? In python I would do it like this:

![image](https://github.com/CEXT-Dan/PyRx/assets/131259064/befadc5d-f2e0-4ae0-892a-52f43fc59276)

**Comment by CEXT-Dan** [comment]
I could have, and probably should have made an alias in C++. And I will start to do this while adding something like 
“Depreciated, please call xxx instead”.

**Comment by CEXT-Dan** [comment]
Couple more notes:

1, I had already renamed all the ‘iterators’, I.e. for BlockTable, BlockTableRecord 
and replaced the with the value type in plural, i.e. block.objectIds()

2, next release v1.3.026, table.cellValues() will return a tuple (nRow, nCol, value) with it’s type intact 
(int, float, and string), dates are still strings 

While it’s my intent to be as close to ARX as possible. AcDbTable is just terrible. The .NET version is an improvement 
There’s lots of things we can do to improve how tables work, and how they behave with pandas and openpyxl 
So, I have some plans for tables .. stay tuned lol
