### ISSUE TITLE
Module is not loaded correctly if it is called test.py

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#77]
Wwhen I load a module called `test.py` using the `PYLOAD` command, I get the message `Success module TEST is loaded` but the commands are not added. The `(pyloaded)` command also sees this module. When I save the same module under a different name, e.g. `test2.py`, and load it again, everything is fine.

_PyRx version <1.3.025.20240614>_

**Comment by CEXT-Dan** [comment]
I can reproduce the issue, but can’t find the bug yet. When I step through the debugger nothing is loaded.
Rx, Ge, Gi, Db, Ap, Ed are not imported. Its like something is loading a ‘test’ module before me.
Either boost, wxPython or Python.

**Comment by gswifort** [comment]
I checked - `test` is a standard python library (for internal use). Check `sys.modules`.I think there is a good reason to consider whether the way of loading modules using `PYLOAD` is good enough.

**Comment by CEXT-Dan** [comment]
I’m sure there’s room for improvement. I tried what was posted here
https://stackoverflow.com/questions/56689051/how-to-import-multiple-python-modules-with-same-name-with-c
doesn’t work though

PyObject *p1 = PyImport_Import( dir.test ); //success
PyModule_GetDict(p1) does not return the dictionary for dir.test 

For now, I’m considering adding some of these module names to the system that checks if a module is already loaded.

I want to consider modules in the same category as ARX or .NET modules, there can only be one.
Of course there will be name collisions, Autodesk had a registered developer symbol at one time to avoid this.
could advise people to prefix their modules

**Comment by CEXT-Dan** [comment]
This is essentially what I am doing in C++

```Python
from pyrx_imp import Rx, Ge, Gi, Db, Ap, Ed
import traceback
import importlib
import os 
import sys

def PyRxCmd_DOIT():
    try:
        path = "C:\\Users\\Dan\\Desktop\\mypy"
        os.chdir(path)
        sys.path.append(path)
        mod = importlib.import_module("test")
        print(mod)
        
    except Exception:
        traceback.print_exc()

#<module 'test' from 'c:\\users\\dan\\appdata\\local\\programs\\python\\python312\\Lib\\test\\__init__.py'>
```

The fix is to compare the paths, fail if they don't match.
Not optimal..  recommendation is to use a more unique module name

**Comment by gswifort** [comment]
I understand that I still can't import the `test.py` module, but now I get an error message..?

**Comment by CEXT-Dan** [comment]
Yeah, I don’t know of a better method. I was thinking of reversing the sys.path, but apparently this is bad practice..

**Comment by gswifort** [comment]
Reversing it is not the best idea, but adding at the beginning of `sys.path ` is probably OK.
This is how python does it, when you have an activated virtual environment it adds local `site-packages` before global.
Likewise, when you run it as a module, it adds the value `'.'` at the beginning of `sys.path`.
True, there is a danger that the user will "overwrite" the standard libraries, but the same danger exists in standard python use.
I'm not saying you should change it, in fact using names from the standard library is not a good idea, but maybe sometimes it's a necessary and purposeful workaround..?
Additionally, the most recently added module is at the end of the search path, which means that previously added modules may already contain other modules with the same name in their search path. Again, this is a user error, but I would probably prefer the last added module to work correctly, rather than the one added at the beginning.
