### ISSUE TITLE
Table setVertCellMargin and setHorzCellMargin not applying.

### ISSUE THREAD

**Issue by Hairo** [CEXT-Dan/PyRx#79]
Not sure if this is a PyRx or OARX issue (considering the function [is marked as deprecated](https://help.autodesk.com/view/OARX/2025/ENU/?guid=OARX-RefGuide-AcDbTable__setVertCellMargin_double)) but when trying to apply margins to a table with:

```
db = Db.curDb()

table = Db.Table()
table.setDatabaseDefaults(db)

table.setSize(len(csv_data)+1, 3)
table.generateLayout()

headers = [("A", 10), ("B", 34), ("C", 38)]
for col, value in enumerate(headers):
    table.setTextString(0, col, value[0])
    table.setColumnWidth(col, value[1])
    table.setTextHeight(0, col, 4.5)

for row, data in enumerate(csv_data):
    for col, value in enumerate(data):
        table.setTextString(row+1, col, str(value))
        table.setAlignment(row+1, col, Db.CellAlignment.kMiddleCenter)
        table.setTextHeight(row+1, col, 4.5)

table.setVertCellMargin(1.2)
table.setHorzCellMargin(4.5)

model = Db.BlockTableRecord(db.modelSpaceId(), Db.OpenMode.kForWrite)
model.appendAcDbEntity(table)
```

The margins stay the same as the default table style (see below): 
![imagen](https://github.com/CEXT-Dan/PyRx/assets/7422368/5d8d6bd2-7359-4333-96f5-eb217aef0015)

Other overrides like column width and text alignment/height are working as intended.

**Comment by kwollaston** [comment]
I should note I also ran in to this issue.

**Comment by Hairo** [comment]
Somehow i missed the `setMargin` function, but setting both bottom and top seems to work:

```
table.setMargin(-1, -1, Db.CellMargin.kCellMarginTop, 1.2)
table.setMargin(-1, -1, Db.CellMargin.kCellMarginBottom, 1.2)
```

**Comment by kwollaston** [comment]
Teamwork makes the dream work!

**Comment by Hairo** [comment]
Yes, it's working for me (only changed top and bottom here):
![imagen](https://github.com/CEXT-Dan/PyRx/assets/7422368/f8067087-d232-43ff-a08e-5f19b0a2ea20)

**Comment by CEXT-Dan** [comment]
I’ll create test cases for these.

**Comment by CEXT-Dan** [comment]
table.setMargin is weird, because it does not except kCellMarginHorzSpacing or kCellMarginVertSpacing, no pun intended 
but you must use one or the ‘or the individual components.. ARX help also kind of implies this. 

```Python
import traceback
from pyrx_impx import Rx, Ge, Gi, Db, Ap, Ed, Ax

def PyRxCmd_doit():
    try:
        db = Db.curDb()
        table = Db.Table()
        table.setDatabaseDefaults(db)
        table.setTableStyle(db.tablestyle())
        table.setSize(5, 5)
        table.generateLayout()
        db.addToModelspace(table)

        v = Db.CellMargin.kCellMarginLeft | Db.CellMargin.kCellMarginRight
        h = Db.CellMargin.kCellMarginTop | Db.CellMargin.kCellMarginBottom
        
        table.setMargin(-1, -1, Db.CellMargin(v), 0.08)
        table.setMargin(-1, -1, Db.CellMargin(h), 0.08)

    except Exception as err:
        traceback.print_exception(err)
```
![table2](https://github.com/CEXT-Dan/PyRx/assets/26830697/7badb573-ab7b-4670-8fff-036e596c781a)

**Comment by Hairo** [comment]
I think it's better to stick to the expected OARX behavior, for consistency sake, maybe make a note about this in the table sample (for future readers), considering that outside of the official documentation OARX info is sparse.

**Comment by CEXT-Dan** [comment]
Added these to the samples, closing this for now
