### ISSUE TITLE
ACAD 2022 + 2025: initget Sample

### ISSUE THREAD

**Issue by kwollaston** [CEXT-Dan/PyRx#88]
There seems to be a bug with the initget sample (or underlying PyRx code).

"Create was pressed" is returned no matter what key word is selected.

It seems like the problem is that when you select a keyword other than the default, the PromptStatus result returns 5100 instead of the expected -5005 as indicated here: https://help.autodesk.com/view/OARX/2025/ENU/?guid=OARX-ManagedRefGuide-Autodesk_AutoCAD_EditorInput_PromptStatus

I don't know if this is because of some setting in my AutoCAD or not, but just bringing it up!

**Comment by CEXT-Dan** [comment]
I don't know why they use HEX in their sample, here's the arx version
https://help.autodesk.com/view/OARX/2023/ENU/?guid=adsk_jsref_acad_promptstatus_function

the wrapper is just

```C++
Acad::PromptStatus PyAcEditor::initGet(int val, const std::string& skwl)
{
    return static_cast<Acad::PromptStatus>(acedInitGet(val, utf8_to_wstr(skwl).c_str()));
}
```

So it's most likely my sample is wonky, I'll get it a spin

**Comment by CEXT-Dan** [comment]
I’ve updated the sample, I hope it works better.
