### ISSUE TITLE
ZWCAD - PyRx lisp function missing

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#94]
Functions `(pyload PATH)` and `(pyloaded)` are not loaded. Also when opening a new document (as mentioned in [#54](https://github.com/CEXT-Dan/PyRx/issues/54#issuecomment-2103974513)).

*PyRx version <1.3.028.20240703>*
*ZWCAD version "25.00_2024.06.20(#11796-51d6b18355a)_x64"*

**Comment by CEXT-Dan** [comment]
Is this a duplicate?

**Comment by CEXT-Dan** [comment]
The functions were renamed  (adspyload)  (adspyloaded) because there’s a bug in ZwCAD 2025’s start page 
 duplicate of ZWCAD disappearing commands #81

**Comment by gswifort** [comment]
I'm sorry, I forgot.

**Comment by CEXT-Dan** [comment]
I didn't see it was fixed, I will make a new compile of v1.3.029
